project_name: pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build
    main: ./examples/base
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/zhenruyan/postgrebase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

release:
  draft: true

archives:
  - id: archive
    builds: [build]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: zip
    files:
      - LICENSE*
      - CHANGELOG*


checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
